copilot() {
  echo ""
  echo "💡 \033[1mReminders\033[0m"
  echo "──────────────────────────────────────────────────────────────────────"
  printf "  \033[1m%-28s\033[0m %s\n" "Shift+Tab → Autopilot" "Long multi-step tasks — runs to completion"
  printf "  \033[1m%-28s\033[0m %s\n" "/ask"      "Side question without polluting history"
  printf "  \033[1m%-28s\033[0m %s\n" "/share"    "Export session as gist/markdown"
  printf "  \033[1m%-28s\033[0m %s\n" "/fleet"    "Run parallel subagents"
  printf "  \033[1m%-28s\033[0m %s\n" "/plan"     "Plan before complex multi-file work"
  printf "  \033[1m%-28s\033[0m %s\n" "/rewind"   "Undo last turn and revert file changes"
  printf "  \033[1m%-28s\033[0m %s\n" "/research" "Deep-dive with GitHub search + web"
  printf "  \033[1m%-28s\033[0m %s\n" "/delegate" "Hand off to cloud agent, runs in background"
  echo "──────────────────────────────────────────────────────────────────────"
  echo ""
  command copilot "$@"
}
